/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
const __create = Object.create;
const __defProp = Object.defineProperty;
const __defProps = Object.defineProperties;
const __getOwnPropDesc = Object.getOwnPropertyDescriptor;
const __getOwnPropDescs = Object.getOwnPropertyDescriptors;
const __getOwnPropNames = Object.getOwnPropertyNames;
const __getOwnPropSymbols = Object.getOwnPropertySymbols;
const __getProtoOf = Object.getPrototypeOf;
const __hasOwnProp = Object.prototype.hasOwnProperty;
const __propIsEnum = Object.prototype.propertyIsEnumerable;
const __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
const __spreadValues = (a, b) => {
  for (const prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (const prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
const __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
const __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
const __export = (target, all) => {
  __markAsModule(target);
  for (const name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
const __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
const __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
const __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    const fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    const rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    const step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => TimeTrackerPlusPlugin
});
const import_obsidian4 = __toModule(require("obsidian"));

// src/settings.ts
const defaultSettings = {
  timestampFormat: "YY-MM-DD HH:mm:ss",
  editableTimestampFormat: "YYYY-MM-DD HH:mm:ss",
  csvDelimiter: ",",
  fineGrainedDurations: true,
  reverseSegmentOrder: false,
  timestampDurations: false,
  autoStopTimes: ""
};

// src/settings-tab.ts
const import_obsidian = __toModule(require("obsidian"));
const TimeTrackerPlusSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    this.containerEl.empty();
    this.containerEl.createEl("h2", { text: "Time Tracker Plus Settings" });
    new import_obsidian.Setting(this.containerEl).setName("Timestamp Display Format").setDesc(createFragment((f) => {
      f.createSpan({ text: "The way that timestamps in time tracker tables should be displayed. Uses " });
      f.createEl("a", { text: "moment.js", href: "https://momentjs.com/docs/#/parsing/string-format/" });
      f.createSpan({ text: " syntax." });
    })).addText((t) => {
      t.setValue(String(this.plugin.settings.timestampFormat));
      t.onChange((v) => __async(this, null, function* () {
        this.plugin.settings.timestampFormat = v.length ? v : defaultSettings.timestampFormat;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(this.containerEl).setName("CSV Delimiter").setDesc("The delimiter character that should be used when copying a tracker table as CSV. For example, some languages use a semicolon instead of a comma.").addText((t) => {
      t.setValue(String(this.plugin.settings.csvDelimiter));
      t.onChange((v) => __async(this, null, function* () {
        this.plugin.settings.csvDelimiter = v.length ? v : defaultSettings.csvDelimiter;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(this.containerEl).setName("Fine-Grained Durations").setDesc("Whether durations should include days, months and years. If this is disabled, additional time units will be displayed as part of the hours.").addToggle((t) => {
      t.setValue(this.plugin.settings.fineGrainedDurations);
      t.onChange((v) => __async(this, null, function* () {
        this.plugin.settings.fineGrainedDurations = v;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(this.containerEl).setName("Timestamp Durations").setDesc("Whether durations should be displayed in a timestamp format (12:15:01) rather than the default duration format (12h 15m 1s).").addToggle((t) => {
      t.setValue(this.plugin.settings.timestampDurations);
      t.onChange((v) => __async(this, null, function* () {
        this.plugin.settings.timestampDurations = v;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(this.containerEl).setName("Display Segments in Reverse Order").setDesc("Whether older tracker segments should be displayed towards the bottom of the tracker, rather than the top.").addToggle((t) => {
      t.setValue(this.plugin.settings.reverseSegmentOrder);
      t.onChange((v) => __async(this, null, function* () {
        this.plugin.settings.reverseSegmentOrder = v;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(this.containerEl).setName("Auto-Stop Times").setDesc("Automatically stop all running timers at specific times each day. Enter times in HH:mm format separated by semicolons (e.g., 11:30;17:30). Leave empty to disable.").addText((t) => {
      t.setPlaceholder("11:30;17:30");
      t.setValue(String(this.plugin.settings.autoStopTimes));
      t.onChange((v) => __async(this, null, function* () {
        this.plugin.settings.autoStopTimes = v;
        yield this.plugin.saveSettings();
      }));
    });
    this.containerEl.createEl("hr");
    this.containerEl.createEl("p", { text: "If you like this plugin and want to support its development, you can buy me a coffee!" });
    const bmcContainer = this.containerEl.createDiv({ cls: "time-tracker-plus-bmc-container" });
    const bmcButton = bmcContainer.createEl("a", {
      href: "https://buymeacoffee.com/hudsonventura",
      attr: { target: "_blank" },
      cls: "time-tracker-plus-bmc-button"
    });
    bmcButton.createSpan({ text: "\u2615", cls: "time-tracker-plus-bmc-icon" });
    bmcButton.createSpan({ text: " Buy me a coffee", cls: "time-tracker-plus-bmc-text" });
  }
};

// src/tracker.ts
const import_obsidian3 = __toModule(require("obsidian"));

// src/confirm-modal.ts
const import_obsidian2 = __toModule(require("obsidian"));
const ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app2, message, callback) {
    super(app2);
    this.message = message;
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("Ok").setCta().onClick(() => {
      this.picked = true;
      this.close();
      this.callback(true);
    })).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.picked = true;
      this.close();
      this.callback(false);
    }));
  }
  onClose() {
    if (!this.picked) {
      this.callback(false);
    }
  }
};
const TargetTimeModal = class extends import_obsidian2.Modal {
  constructor(app2, callback) {
    super(app2);
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Set Target Time" });
    contentEl.createEl("p", { text: "Enter target time (e.g., 2h, 30m, 1h30m, 2d5h):" });
    let textInput;
    new import_obsidian2.Setting(contentEl).setName("Target Time").addText((text) => {
      textInput = text;
      text.setPlaceholder("2h");
      text.inputEl.focus();
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.picked = true;
          this.close();
          this.callback(text.getValue());
        }
      });
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("Ok").setCta().onClick(() => {
      this.picked = true;
      this.close();
      this.callback(textInput.getValue());
    })).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.picked = true;
      this.close();
      this.callback(null);
    }));
  }
  onClose() {
    if (!this.picked) {
      this.callback(null);
    }
  }
};

// src/tracker.ts
function saveTracker(tracker, fileName, section) {
  return __async(this, null, function* () {
    let file = app.vault.getAbstractFileByPath(fileName);
    if (!file)
      return;
    let content = yield app.vault.read(file);
    let lines = content.split("\n");
    let prev = lines.filter((_, i) => i <= section.lineStart).join("\n");
    let next = lines.filter((_, i) => i >= section.lineEnd).join("\n");
    content = `${prev}
${JSON.stringify(tracker)}
${next}`;
    yield app.vault.modify(file, content);
  });
}
function loadTracker(json) {
  if (json) {
    try {
      let ret = JSON.parse(json);
      updateLegacyInfo(ret.entries);
      return ret;
    } catch (e) {
      console.log(`Failed to parse Tracker from ${json}`);
    }
  }
  return { entries: [] };
}
function loadAllTrackers(fileName) {
  return __async(this, null, function* () {
    let file = app.vault.getAbstractFileByPath(fileName);
    let content = (yield app.vault.cachedRead(file)).split("\n");
    let trackers = [];
    let curr;
    for (let i = 0; i < content.length; i++) {
      let line = content[i];
      if (line.trimEnd() == "```time-tracker-plus") {
        curr = { lineStart: i + 1, text: "" };
      } else if (curr) {
        if (line.trimEnd() == "```") {
          curr.lineEnd = i - 1;
          let tracker = loadTracker(curr.text);
          trackers.push({ section: curr, tracker });
          curr = void 0;
        } else {
          curr.text += `${line}
`;
        }
      }
    }
    return trackers;
  });
}
function displayTracker(tracker, element, getFile, getSectionInfo, settings, component, app2) {
  element.addClass("time-tracker-plus-container");
  let running = isRunning(tracker);
  let newSegmentNameBox = { getValue: () => "" };
  let durationCells = [];
  let progressBar, progressFill, progressText;
  if (tracker.entries.length > 0) {
    let table = element.createEl("table", { cls: "time-tracker-plus-table" });
    table.createEl("tr").append(createEl("th", { text: "Segment" }), createEl("th", { text: "Start time" }), createEl("th", { text: "End time" }), createEl("th", { text: "Duration" }), createEl("th"));
    if (tracker.targetTime) {
      let progressRow = table.createEl("tr", { cls: "time-tracker-plus-progress-row" });
      let progressCell = progressRow.createEl("td", { attr: { colspan: "5" } });
      let progressContainer = progressCell.createEl("div", { cls: "time-tracker-plus-progress-container-inline" });
      progressBar = progressContainer.createEl("div", { cls: "time-tracker-plus-progress-bar" });
      progressFill = progressBar.createEl("div", { cls: "time-tracker-plus-progress-fill" });
      if (running) {
        progressFill.addClass("time-tracker-plus-progress-running");
      }
      progressText = progressContainer.createEl("div", { cls: "time-tracker-plus-progress-text" });
    }
    for (let entry of orderedEntries(tracker.entries, settings))
      addEditableTableRow(tracker, entry, table, newSegmentNameBox, running, getFile, getSectionInfo, settings, 0, component, durationCells, app2);
    let intervalId = window.setInterval(() => {
      if (!element.isConnected) {
        window.clearInterval(intervalId);
        return;
      }
      for (let { entry, cell } of durationCells) {
        cell.setText(formatDuration(getDuration(entry), settings));
      }
      if (tracker.targetTime && progressFill && progressText) {
        updateProgressBar(tracker, progressFill, progressText, settings);
      }
    }, 1e3);
    if (tracker.targetTime && progressFill && progressText) {
      updateProgressBar(tracker, progressFill, progressText, settings);
    }
  } else {
    let btn = new import_obsidian3.ButtonComponent(element).setClass("clickable-icon").setIcon("lucide-play-circle").setTooltip("Start").onClick(() => __async(this, null, function* () {
      yield stopAllOtherRunningTimers(app2, getFile());
      startNewEntry(tracker, newSegmentNameBox.getValue());
      yield saveTracker(tracker, getFile(), getSectionInfo());
    }));
    btn.buttonEl.addClass("time-tracker-plus-btn");
  }
}
function updateProgressBar(tracker, progressFill, progressText, settings) {
  const totalDuration = getTotalDuration(tracker.entries);
  const targetDuration = parseTargetTime(tracker.targetTime);
  if (targetDuration > 0) {
    const percentage = Math.min(100, totalDuration / targetDuration * 100);
    progressFill.setCssStyles({ "--time-tracker-plus-progress-width": `${percentage}%` });
    const runningText = isRunning(tracker) ? " ● RUNNING" : "";
    progressText.setText(`${formatDuration(totalDuration, settings)} / ${tracker.targetTime} (${percentage.toFixed(1)}%)${runningText}`);
    if (isRunning(tracker)) {
      progressText.addClass("time-tracker-plus-progress-text-running");
    } else {
      progressText.removeClass("time-tracker-plus-progress-text-running");
    }
  }
}
function parseTargetTime(targetTime) {
  if (!targetTime)
    return 0;
  const regex = /(?:(\d+)y)?(?:(\d+)M)?(?:(\d+)d)?(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?/;
  const match = targetTime.match(regex);
  if (!match)
    return 0;
  const years = parseInt(match[1] || "0");
  const months = parseInt(match[2] || "0");
  const days = parseInt(match[3] || "0");
  const hours = parseInt(match[4] || "0");
  const minutes = parseInt(match[5] || "0");
  const seconds = parseInt(match[6] || "0");
  return (years * 365 * 24 * 60 * 60 + months * 30 * 24 * 60 * 60 + days * 24 * 60 * 60 + hours * 60 * 60 + minutes * 60 + seconds) * 1e3;
}
function getDuration(entry) {
  if (entry.subEntries) {
    return getTotalDuration(entry.subEntries);
  } else {
    let endTime = entry.endTime ? (0, import_obsidian3.moment)(entry.endTime) : (0, import_obsidian3.moment)();
    return endTime.diff((0, import_obsidian3.moment)(entry.startTime));
  }
}
function getDurationToday(entry) {
  if (entry.subEntries) {
    return getTotalDurationToday(entry.subEntries);
  } else {
    let today = (0, import_obsidian3.moment)().startOf("day");
    let endTime = entry.endTime ? (0, import_obsidian3.moment)(entry.endTime) : (0, import_obsidian3.moment)();
    let startTime = (0, import_obsidian3.moment)(entry.startTime);
    if (endTime.isBefore(today)) {
      return 0;
    }
    if (startTime.isBefore(today)) {
      startTime = today;
    }
    return endTime.diff(startTime);
  }
}
function getTotalDuration(entries) {
  let ret = 0;
  for (let entry of entries)
    ret += getDuration(entry);
  return ret;
}
function getTotalDurationToday(entries) {
  let ret = 0;
  for (let entry of entries)
    ret += getDurationToday(entry);
  return ret;
}
function isRunning(tracker) {
  return !!getRunningEntry(tracker.entries);
}
function getRunningEntry(entries) {
  for (let entry of entries) {
    if (entry.subEntries) {
      let running = getRunningEntry(entry.subEntries);
      if (running)
        return running;
    } else {
      if (!entry.endTime)
        return entry;
    }
  }
  return null;
}
function createMarkdownTable(tracker, settings) {
  let table = [["Segment", "Start time", "End time", "Duration"]];
  for (let entry of orderedEntries(tracker.entries, settings))
    table.push(...createTableSection(entry, settings));
  table.push(["**Total**", "", "", `**${formatDuration(getTotalDuration(tracker.entries), settings)}**`]);
  let ret = "";
  let widths = Array.from(Array(4).keys()).map((i) => Math.max(...table.map((a) => a[i].length)));
  for (let r = 0; r < table.length; r++) {
    if (r == 1)
      ret += "| " + Array.from(Array(4).keys()).map((i) => "-".repeat(widths[i])).join(" | ") + " |\n";
    let row = [];
    for (let i = 0; i < 4; i++)
      row.push(table[r][i].padEnd(widths[i], " "));
    ret += "| " + row.join(" | ") + " |\n";
  }
  return ret;
}
function createCsv(tracker, settings) {
  let ret = "";
  for (let entry of orderedEntries(tracker.entries, settings)) {
    for (let row of createTableSection(entry, settings))
      ret += row.join(settings.csvDelimiter) + "\n";
  }
  return ret;
}
function orderedEntries(entries, settings) {
  return settings.reverseSegmentOrder ? entries.slice().reverse() : entries;
}
function formatTimestamp(timestamp, settings) {
  return (0, import_obsidian3.moment)(timestamp).format(settings.timestampFormat);
}
function formatDuration(totalTime, settings) {
  let ret = "";
  let duration = import_obsidian3.moment.duration(totalTime);
  let hours = settings.fineGrainedDurations ? duration.hours() : Math.floor(duration.asHours());
  if (settings.timestampDurations) {
    if (settings.fineGrainedDurations) {
      let days = Math.floor(duration.asDays());
      if (days > 0)
        ret += days + ".";
    }
    ret += `${hours.toString().padStart(2, "0")}:${duration.minutes().toString().padStart(2, "0")}:${duration.seconds().toString().padStart(2, "0")}`;
  } else {
    if (settings.fineGrainedDurations) {
      let years = Math.floor(duration.asYears());
      if (years > 0)
        ret += years + "y ";
      if (duration.months() > 0)
        ret += duration.months() + "M ";
      if (duration.days() > 0)
        ret += duration.days() + "d ";
    }
    if (hours > 0)
      ret += hours + "h ";
    if (duration.minutes() > 0)
      ret += duration.minutes() + "m ";
    ret += duration.seconds() + "s";
  }
  return ret;
}
function startSubEntry(entry, name) {
  if (!entry.subEntries) {
    entry.subEntries = [__spreadProps(__spreadValues({}, entry), { name: `Part 1` })];
    entry.startTime = null;
    entry.endTime = null;
  }
  if (!name)
    name = `Part ${entry.subEntries.length + 1}`;
  entry.subEntries.push({ name, startTime: (0, import_obsidian3.moment)().toISOString(), endTime: null, subEntries: void 0 });
}
function startNewEntry(tracker, name) {
  if (!name)
    name = `Segment ${tracker.entries.length + 1}`;
  let entry = { name, startTime: (0, import_obsidian3.moment)().toISOString(), endTime: null, subEntries: void 0 };
  tracker.entries.push(entry);
}
function endRunningEntry(tracker) {
  let entry = getRunningEntry(tracker.entries);
  entry.endTime = (0, import_obsidian3.moment)().toISOString();
}
function endRunningEntryInSegment(entry) {
  if (entry.subEntries) {
    let running = getRunningEntry(entry.subEntries);
    if (running) {
      running.endTime = (0, import_obsidian3.moment)().toISOString();
    }
  } else if (!entry.endTime) {
    entry.endTime = (0, import_obsidian3.moment)().toISOString();
  }
}
function hasRunningEntry(entry) {
  if (entry.subEntries) {
    return getRunningEntry(entry.subEntries) != null;
  } else {
    return !entry.endTime;
  }
}
function removeEntry(entries, toRemove) {
  if (entries.contains(toRemove)) {
    entries.remove(toRemove);
    return true;
  } else {
    for (let entry of entries) {
      if (entry.subEntries && removeEntry(entry.subEntries, toRemove)) {
        if (entry.subEntries.length == 1) {
          let single = entry.subEntries[0];
          entry.startTime = single.startTime;
          entry.endTime = single.endTime;
          entry.subEntries = void 0;
        }
        return true;
      }
    }
  }
  return false;
}
function setCountdownValues(tracker, current, total, totalToday, currentDiv, settings) {
  let running = getRunningEntry(tracker.entries);
  if (running && !running.endTime) {
    current.setText(formatDuration(getDuration(running), settings));
    currentDiv.hidden = false;
  } else {
    currentDiv.hidden = true;
  }
  total.setText(formatDuration(getTotalDuration(tracker.entries), settings));
  totalToday == null ? void 0 : totalToday.setText(formatDuration(getTotalDurationToday(tracker.entries), settings));
}
function formatEditableTimestamp(timestamp, settings) {
  return (0, import_obsidian3.moment)(timestamp).format(settings.editableTimestampFormat);
}
function unformatEditableTimestamp(formatted, settings) {
  return (0, import_obsidian3.moment)(formatted, settings.editableTimestampFormat).toISOString();
}
function updateLegacyInfo(entries) {
  for (let entry of entries) {
    if (entry.startTime && !isNaN(+entry.startTime))
      entry.startTime = import_obsidian3.moment.unix(+entry.startTime).toISOString();
    if (entry.endTime && !isNaN(+entry.endTime))
      entry.endTime = import_obsidian3.moment.unix(+entry.endTime).toISOString();
    if (entry.subEntries == null || !entry.subEntries.length)
      entry.subEntries = void 0;
    if (entry.subEntries)
      updateLegacyInfo(entry.subEntries);
  }
}
function createTableSection(entry, settings, indent = 0) {
  const prefix = `${"-".repeat(indent)} `;
  let ret = [[
    `${prefix}${entry.name}`,
    entry.startTime ? formatTimestamp(entry.startTime, settings) : "",
    entry.endTime ? formatTimestamp(entry.endTime, settings) : "",
    entry.endTime || entry.subEntries ? formatDuration(getDuration(entry), settings) : ""
  ]];
  if (entry.subEntries) {
    for (let sub of orderedEntries(entry.subEntries, settings))
      ret.push(...createTableSection(sub, settings, indent + 1));
  }
  return ret;
}
function addEditableTableRow(tracker, entry, table, newSegmentNameBox, trackerRunning, getFile, getSectionInfo, settings, indent, component, durationCells, app2) {
  let entryRunning = hasRunningEntry(entry);
  let row = table.createEl("tr");
  if (entryRunning) {
    row.addClass("time-tracker-plus-running");
  }
  let nameField = new EditableField(row, indent, entry.name);
  let startField = new EditableTimestampField(row, entry.startTime, settings);
  let endField = new EditableTimestampField(row, entry.endTime, settings);
  let durationCell = row.createEl("td", { text: formatDuration(getDuration(entry), settings) });
  if (entryRunning) {
    durationCell.addClass("time-tracker-plus-duration-running");
    let runningIndicator = nameField.cell.createSpan({ cls: "time-tracker-plus-running-indicator", text: " ● RUNNING" });
  }
  if (durationCells) {
    durationCells.push({ entry, cell: durationCell });
  }
  renderNameAsMarkdown(nameField.label, getFile, component);
  let expandButton = new import_obsidian3.ButtonComponent(nameField.label).setClass("clickable-icon").setClass("time-tracker-plus-expand-button").setIcon(`chevron-${entry.collapsed ? "left" : "down"}`).onClick(() => __async(this, null, function* () {
    if (entry.collapsed) {
      entry.collapsed = void 0;
    } else {
      entry.collapsed = true;
    }
    yield saveTracker(tracker, getFile(), getSectionInfo());
  }));
  if (!entry.subEntries)
    expandButton.buttonEl.addClass("time-tracker-plus-expand-button-hidden");
  let entryButtons = row.createEl("td");
  entryButtons.addClass("time-tracker-plus-table-buttons");
  if (indent === 0) {
    new import_obsidian3.ButtonComponent(entryButtons).setClass("clickable-icon").setIcon(`lucide-play`).setTooltip("Continue").setDisabled(trackerRunning).onClick(() => __async(this, null, function* () {
      yield stopAllOtherRunningTimers(app2, getFile());
      startSubEntry(entry, newSegmentNameBox.getValue());
      yield saveTracker(tracker, getFile(), getSectionInfo());
    }));
    new import_obsidian3.ButtonComponent(entryButtons).setClass("clickable-icon").setIcon(`lucide-stop-circle`).setTooltip("Stop").setDisabled(!entryRunning).onClick(() => __async(this, null, function* () {
      endRunningEntryInSegment(entry);
      yield saveTracker(tracker, getFile(), getSectionInfo());
    }));
  }
  let editButton = new import_obsidian3.ButtonComponent(entryButtons).setClass("clickable-icon").setTooltip("Edit").setIcon("lucide-pencil").onClick(() => __async(this, null, function* () {
    yield handleEdit();
  }));
  nameField.label.addEventListener("dblclick", () => __async(this, null, function* () {
    if (!nameField.editing()) {
      yield handleEdit();
    }
  }));
  function handleEdit() {
    return __async(this, null, function* () {
      if (nameField.editing()) {
        yield saveChanges();
      } else {
        startEditing();
      }
    });
  }
  function saveChanges() {
    return __async(this, null, function* () {
      entry.name = nameField.endEdit();
      expandButton.buttonEl.removeClass("time-tracker-plus-expand-button-editing");
      startField.endEdit();
      entry.startTime = startField.getTimestamp();
      if (!entryRunning) {
        endField.endEdit();
        entry.endTime = endField.getTimestamp();
      }
      yield saveTracker(tracker, getFile(), getSectionInfo());
      editButton.setIcon("lucide-pencil");
      renderNameAsMarkdown(nameField.label, getFile, component);
    });
  }
  function startEditing() {
    nameField.beginEdit(entry.name, true);
    expandButton.buttonEl.addClass("time-tracker-plus-expand-button-editing");
    if (!entry.subEntries) {
      startField.beginEdit(entry.startTime);
      if (!entryRunning)
        endField.beginEdit(entry.endTime);
    }
    editButton.setIcon("lucide-check");
    nameField.onSave = startField.onSave = endField.onSave = () => __async(this, null, function* () {
      yield saveChanges();
    });
    nameField.onCancel = startField.onCancel = endField.onCancel = () => {
      nameField.endEdit();
      startField.endEdit();
      if (!entryRunning) {
        endField.endEdit();
      }
      expandButton.buttonEl.removeClass("time-tracker-plus-expand-button-editing");
      editButton.setIcon("lucide-pencil");
    };
  }
  new import_obsidian3.ButtonComponent(entryButtons).setClass("clickable-icon").setTooltip("Remove").setIcon("lucide-trash").setDisabled(entryRunning).onClick(() => __async(this, null, function* () {
    const confirmed = yield showConfirm("Are you sure you want to delete this entry?");
    if (!confirmed) {
      return;
    }
    removeEntry(tracker.entries, entry);
    yield saveTracker(tracker, getFile(), getSectionInfo());
  }));
  if (entry.subEntries && !entry.collapsed) {
    for (let sub of orderedEntries(entry.subEntries, settings))
      addEditableTableRow(tracker, sub, table, newSegmentNameBox, trackerRunning, getFile, getSectionInfo, settings, indent + 1, component, durationCells, app2);
  }
}
function showConfirm(message) {
  return new Promise((resolve) => {
    const modal = new ConfirmModal(app, message, resolve);
    modal.open();
  });
}
function renderNameAsMarkdown(label, getFile, component) {
  const text = label.textContent || "";
  label.empty();
  void import_obsidian3.MarkdownRenderer.render(app, text, label, getFile(), component).then(() => {
    const paragraph = label.querySelector("p");
    if (paragraph) {
      while (paragraph.firstChild) {
        label.appendChild(paragraph.firstChild);
      }
      paragraph.remove();
    }
  });
}
const EditableField = class {
  constructor(row, indent, value) {
    this.cell = row.createEl("td");
    this.label = this.cell.createEl("span", { text: value, cls: "time-tracker-plus-field-indent" });
    this.label.setCssStyles({ "--time-tracker-plus-indent": `${indent}em` });
    this.box = new import_obsidian3.TextComponent(this.cell).setValue(value);
    this.box.inputEl.addClass("time-tracker-plus-input");
    this.box.inputEl.hide();
    this.box.inputEl.addEventListener("keydown", (e) => {
      let _a, _b;
      if (e.key === "Enter") {
        e.preventDefault();
        (_a = this.onSave) == null ? void 0 : _a.call(this);
      }
      if (e.key === "Escape") {
        e.preventDefault();
        (_b = this.onCancel) == null ? void 0 : _b.call(this);
      }
    });
  }
  editing() {
    return this.label.hidden;
  }
  beginEdit(value, focus = false) {
    this.label.hidden = true;
    this.box.setValue(value);
    this.box.inputEl.show();
    if (focus)
      this.box.inputEl.focus();
  }
  endEdit() {
    const value = this.box.getValue();
    this.label.setText(value);
    this.box.inputEl.hide();
    this.label.hidden = false;
    return value;
  }
};
const EditableTimestampField = class extends EditableField {
  constructor(row, value, settings) {
    super(row, 0, value ? formatTimestamp(value, settings) : "");
    this.settings = settings;
  }
  beginEdit(value, focus = false) {
    super.beginEdit(value ? formatEditableTimestamp(value, this.settings) : "", focus);
  }
  endEdit() {
    const value = this.box.getValue();
    let displayValue = value;
    if (value) {
      const timestamp = unformatEditableTimestamp(value, this.settings);
      displayValue = formatTimestamp(timestamp, this.settings);
    }
    this.label.setText(displayValue);
    this.box.inputEl.hide();
    this.label.hidden = false;
    return value;
  }
  getTimestamp() {
    if (this.box.getValue()) {
      return unformatEditableTimestamp(this.box.getValue(), this.settings);
    } else {
      return null;
    }
  }
};

// src/main.ts
function shouldAutoStopNow(autoStopTimes) {
  if (!autoStopTimes || autoStopTimes.trim() === "") {
    return false;
  }
  const now = (0, import_obsidian3.moment)();
  const currentTime = now.format("HH:mm");
  const times = autoStopTimes.split(";").map((t) => t.trim()).filter((t) => t);
  return times.includes(currentTime);
}
function stopAllRunnersInFile(fileContent, fileName, app2) {
  return __async(this, null, function* () {
    const codeBlockRegex = /```time-tracker-plus\n([\s\S]*?)\n```/g;
    let match;
    let modified = false;
    let newContent = fileContent;
    while ((match = codeBlockRegex.exec(fileContent)) !== null) {
      try {
        const tracker = JSON.parse(match[1]);
        if (isRunning(tracker)) {
          const runningEntry = getRunningEntry(tracker.entries);
          if (runningEntry) {
            runningEntry.endTime = (0, import_obsidian3.moment)().toISOString();
            const updatedTracker = JSON.stringify(tracker);
            newContent = newContent.replace(match[0], `\`\`\`time-tracker-plus
${updatedTracker}
\`\`\``);
            modified = true;
          }
        }
      } catch (e) {
      }
    }
    if (modified) {
      const file = app2.vault.getAbstractFileByPath(fileName);
      if (file instanceof import_obsidian4.TFile) {
        yield app2.vault.modify(file, newContent);
      }
    }
    return modified;
  });
}
function stopAllOtherRunningTimers(app2, currentFileName) {
  return __async(this, null, function* () {
    const files = app2.vault.getMarkdownFiles();
    for (const file of files) {
      try {
        const content = yield app2.vault.read(file);
        yield stopAllRunnersInFile(content, file.path, app2);
      } catch (e) {
        console.error("Error stopping timers in file:", file.path, e);
      }
    }
  });
}
const TimeTrackerPlusPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.api = {
      loadTracker,
      loadAllTrackers,
      getDuration,
      getTotalDuration,
      getDurationToday,
      getTotalDurationToday,
      getRunningEntry,
      isRunning,
      formatTimestamp: (timestamp) => formatTimestamp(timestamp, this.settings),
      formatDuration: (totalTime) => formatDuration(totalTime, this.settings),
      orderedEntries: (entries) => orderedEntries(entries, this.settings)
    };
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(new TimeTrackerPlusSettingsTab(this.app, this));
      this.registerMarkdownCodeBlockProcessor("time-tracker-plus", (s, e, i) => {
        e.empty();
        let component = new import_obsidian4.MarkdownRenderChild(e);
        let tracker = loadTracker(s);
        let filePath = i.sourcePath;
        const getFile = () => filePath;
        component.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
          if (file instanceof import_obsidian4.TFile && oldPath === filePath) {
            filePath = file.path;
          }
        }));
        displayTracker(tracker, e, getFile, () => i.getSectionInfo(e), this.settings, component, this.app);
        i.addChild(component);
      });
      this.addCommand({
        id: `insert`,
        name: `Insert Time Tracker`,
        editorCallback: (e, _) => {
          const modal = new TargetTimeModal(this.app, (targetTime) => {
            let tracker = { entries: [] };
            if (targetTime && targetTime.trim()) {
              tracker.targetTime = targetTime.trim();
            }
            e.replaceSelection(`\`\`\`time-tracker-plus
${JSON.stringify(tracker)}
\`\`\`
`);
          });
          modal.open();
        }
      });
      this.addCommand({
        id: `stop-all-timers`,
        name: `Stop All Running Timers`,
        callback: () => __async(this, null, function* () {
          let stoppedCount = 0;
          const files = this.app.vault.getMarkdownFiles();
          for (const file of files) {
            try {
              const content = yield this.app.vault.read(file);
              const wasStopped = yield stopAllRunnersInFile(content, file.path, this.app);
              if (wasStopped) {
                stoppedCount++;
              }
            } catch (e) {
              console.error("Error stopping timers in file:", file.path, e);
            }
          }
          if (stoppedCount > 0) {
            new import_obsidian4.Notice(`Stopped running timers in ${stoppedCount} file(s)`);
          } else {
            new import_obsidian4.Notice("No running timers found");
          }
        })
      });
      let lastCheckedMinute = -1;
      const autoStopInterval = window.setInterval(() => __async(this, null, function* () {
        const now = (0, import_obsidian3.moment)();
        const currentMinute = now.minutes();
        if (currentMinute === lastCheckedMinute) {
          return;
        }
        lastCheckedMinute = currentMinute;
        if (shouldAutoStopNow(this.settings.autoStopTimes)) {
          let stoppedCount = 0;
          const files = this.app.vault.getMarkdownFiles();
          for (const file of files) {
            try {
              const content = yield this.app.vault.read(file);
              const wasStopped = yield stopAllRunnersInFile(content, file.path, this.app);
              if (wasStopped) {
                stoppedCount++;
              }
            } catch (e) {
              console.error("Error auto-stopping timers in file:", file.path, e);
            }
          }
          if (stoppedCount > 0) {
            new import_obsidian4.Notice(`Auto-stopped timers in ${stoppedCount} file(s) at ${now.format("HH:mm")}`);
          }
        }
      }), 1e3);
      this.registerInterval(autoStopInterval);
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, defaultSettings, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings); 
    });
  }
};

/* nosourcemap */